### ISSUE TITLE
Release tracker - v0.1.0

### ISSUE THREAD

**Issue by frgfm** [frgfm/ghapi#5]
This issue is to be used to track the roadmap of ghapi for release v0.1.0, and collect feedback from users & contributors.

**Supported features**
- [x] Parse a Pull Request (#1, #3)
- [x] Reviews (stage comments & submit reviews) (#6)
- [x] List reviews of a given repository (#11)
